//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_Bookstore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book_Inventory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book_Inventory()
        {
            this.Shopping_Cart = new HashSet<Shopping_Cart>();
            this.purchase_history = new HashSet<purchase_history>();
        }
    
        public int book_id { get; set; }
        public string book_title { get; set; }
        public string book_author { get; set; }
        public string book_descreption { get; set; }
        public int price { get; set; }
        public byte[] book_img { get; set; }
        public Nullable<int> category_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shopping_Cart> Shopping_Cart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchase_history> purchase_history { get; set; }
        public virtual category category { get; set; }
    }
}
