//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_Bookstore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shopping_Cart
    {
        public int shoppingcartid { get; set; }
        public int book_id { get; set; }
        public int price { get; set; }
        public int user_id { get; set; }
        public System.DateTime date { get; set; }
        public int quantity { get; set; }
    
        public virtual Book_Inventory Book_Inventory { get; set; }
        public virtual user user { get; set; }
    }
}
